" Tinmarino's vimrc for vim.js

silent exec '!console.log("tinp: vimrc 4")'

set nocp

ru script/net.vim
ru script/color.vim
ru script/plugin.vim




" Use monospace fonts only!
set guifont=14px\ \"Source\ Code\ Pro\"\\,monospace

silent so $VIMRUNTIME/syntax/syntax.vim
colorscheme Darkside


"========== MAP ==========
" As autocmd otherwise CR is interpreted ... 
function! TinMap()

map gf gEWvE"fy:call ReadWrapper(@f)<CR>
map gx gEWvE"fy:call OpenXref(@f)<CR>
map gs :call DownloadFile()<CR>
map <F8> :call Colorinc(1)<CR>
map <S-F8> :call Colorinc(-1)<CR>
inoremap jk <esc>
inoremap kj <esc>

endfunction  " TinMap
au VimEnter * call TinMap()


"========== OTHERS ==========
" Some are actually not yet supported
set number
set wildmenu
set tabstop=4
set expandtab
set nocompatible
set fileencodings=utf8
set nowrap
set encoding=utf8
set termencoding=utf8
set backspace=indent,eol,start
set wildmode=longest,list,full
set mouse=a
set shiftwidth=4

"========== PLUGGIN ==========



"========== EXPERIMENTAL (not in Vim) ==========
" Read local files
" :bro e local

" Read files from Dropbox
" :bro e dropbox

" Call JavaScript (Note the escape of !)

" If you are editing a JavaScript file:
" :!%

" emscripten API works:
" :!FS.mkdir('/foo')

